openapi: 3.0.3
info:
  title: Mock DID:ION Service
  version: 1.0.0
  description: A mock service for simulating DID:ION functionality in the Solid VC Microservices Prototype
  contact:
    name: PDS3.0 Build Team
  license:
    name: MIT

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.mock-did-ion.example.com
    description: Production server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time
                  service:
                    type: string
                    example: Mock DID:ION Service
                  version:
                    type: string
                    example: 1.0.0

  /did/create:
    post:
      summary: Create new DID:ION
      description: Creates a new DID:ION identifier with the provided public key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - publicKey
              properties:
                publicKey:
                  type: string
                  description: Base58-encoded public key
                  example: 3M2mTGjHSXzpzVcxUjGCDNDHn5M9ux4rGqF8RpqBsHQA
                keyType:
                  type: string
                  enum: [Ed25519, RSA, secp256k1]
                  description: Type of cryptographic key
                  default: Ed25519
      responses:
        '201':
          description: DID created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/DIDCreateResponse'
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /did/resolve/{did}:
    get:
      summary: Resolve DID document
      description: Retrieves the DID document for the specified DID
      parameters:
        - name: did
          in: path
          required: true
          schema:
            type: string
            pattern: '^did:ion:.+$'
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
      responses:
        '200':
          description: DID document resolved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/DIDResolveResponse'
                  timestamp:
                    type: string
                    format: date-time
        '404':
          description: DID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Invalid DID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /did/verify:
    post:
      summary: Verify signature
      description: Verifies a signature against a DID's public key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - did
                - data
                - signature
              properties:
                did:
                  type: string
                  pattern: '^did:ion:.+$'
                  description: The DID to verify against
                  example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
                data:
                  type: string
                  description: The data that was signed
                  example: Hello, World!
                signature:
                  type: string
                  description: The signature to verify
                  example: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
                keyId:
                  type: string
                  description: Optional specific key ID to use for verification
                  example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w#key-1
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/VerifyResponse'
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /did/list:
    get:
      summary: List all DIDs (testing endpoint)
      description: Returns a list of all DIDs in the registry for testing purposes
      responses:
        '200':
          description: List of DIDs
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      dids:
                        type: array
                        items:
                          $ref: '#/components/schemas/DIDState'
                      count:
                        type: number
                        example: 5
                  timestamp:
                    type: string
                    format: date-time

  /did/{did}:
    delete:
      summary: Deactivate a DID (testing endpoint)
      description: Deactivates a DID for testing purposes
      parameters:
        - name: did
          in: path
          required: true
          schema:
            type: string
            pattern: '^did:ion:.+$'
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
      responses:
        '200':
          description: DID deactivated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        example: DID deactivated successfully
                  timestamp:
                    type: string
                    format: date-time
        '404':
          description: DID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    Service:
      type: object
      properties:
        id:
          type: string
          description: Service identifier
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w#service-1
        type:
          type: string
          description: Service type
          example: LinkedDomains
        serviceEndpoint:
          oneOf:
            - type: string
              description: Service endpoint URI
              example: https://example.com
            - type: array
              description: Multiple service endpoints
              items:
                type: string
                example: https://example.com
            - type: object
              description: Complex service endpoint definition
              additionalProperties: true

    DIDCreateResponse:
      type: object
      properties:
        did:
          type: string
          pattern: '^did:ion:.+$'
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
        document:
          $ref: '#/components/schemas/DIDDocument'
        created:
          type: string
          format: date-time
        transactionId:
          type: string
          description: The ID of the creation transaction
          example: 5f8d7a9b2c3e4f1a0b9c8d7e6f5a4b3c

    DIDUpdateResponse:
      type: object
      properties:
        did:
          type: string
          description: The updated DID
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
        transactionId:
          type: string
          description: The ID of the update transaction
          example: 5f8d7a9b2c3e4f1a0b9c8d7e6f5a4b3c
        status:
          type: string
          enum: [pending, anchored]
          description: Status of the update operation
          example: pending
        document:
          $ref: '#/components/schemas/DIDDocument'

    DIDRecoverResponse:
      type: object
      properties:
        did:
          type: string
          description: The recovered DID
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
        transactionId:
          type: string
          description: The ID of the recovery transaction
          example: 5f8d7a9b2c3e4f1a0b9c8d7e6f5a4b3c
        status:
          type: string
          enum: [pending, anchored]
          description: Status of the recovery operation
          example: pending
        document:
          $ref: '#/components/schemas/DIDDocument'

    DIDDeactivateResponse:
      type: object
      properties:
        did:
          type: string
          description: The deactivated DID
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
        transactionId:
          type: string
          description: The ID of the deactivation transaction
          example: 5f8d7a9b2c3e4f1a0b9c8d7e6f5a4b3c
        status:
          type: string
          enum: [pending, anchored]
          description: Status of the deactivation operation
          example: pending

    TransactionStatus:
      type: object
      properties:
        id:
          type: string
          description: The transaction ID
          example: 5f8d7a9b2c3e4f1a0b9c8d7e6f5a4b3c
        did:
          type: string
          description: The DID associated with the transaction
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
        type:
          type: string
          enum: [create, update, recover, deactivate]
          description: The type of operation
          example: update
        status:
          type: string
          enum: [pending, anchored, failed]
          description: The status of the transaction
          example: pending
        timestamp:
          type: string
          format: date-time
          description: When the transaction was initiated
        anchoredAt:
          type: string
          format: date-time
          description: When the transaction was anchored (if applicable)
        error:
          type: string
          description: Error message if the transaction failed

    Operation:
      type: object
      properties:
        id:
          type: string
          description: The operation ID
          example: 5f8d7a9b2c3e4f1a0b9c8d7e6f5a4b3c
        type:
          type: string
          enum: [create, update, recover, deactivate]
          description: The type of operation
          example: create
        timestamp:
          type: string
          format: date-time
          description: When the operation was performed
        status:
          type: string
          enum: [pending, anchored, failed]
          description: The status of the operation
          example: anchored
        transactionId:
          type: string
          description: Associated transaction ID
          example: 5f8d7a9b2c3e4f1a0b9c8d7e6f5a4b3c

    DIDResolveResponse:
      type: object
      properties:
        didDocument:
          $ref: '#/components/schemas/DIDDocument'
        didDocumentMetadata:
          type: object
          properties:
            created:
              type: string
              format: date-time
            updated:
              type: string
              format: date-time
            deactivated:
              type: boolean
        didResolutionMetadata:
          type: object
          properties:
            contentType:
              type: string
              example: application/did+ld+json

    DIDDocument:
      type: object
      properties:
        '@context':
          type: array
          items:
            type: string
          example: 
            - https://www.w3.org/ns/did/v1
            - https://w3id.org/security/suites/ed25519-2020/v1
        id:
          type: string
          pattern: '^did:ion:.+$'
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w
        verificationMethod:
          type: array
          items:
            $ref: '#/components/schemas/VerificationMethod'
        authentication:
          type: array
          items:
            type: string
        assertionMethod:
          type: array
          items:
            type: string
        keyAgreement:
          type: array
          items:
            type: string
        capabilityInvocation:
          type: array
          items:
            type: string
        capabilityDelegation:
          type: array
          items:
            type: string
        service:
          type: array
          items:
            $ref: '#/components/schemas/Service'

    VerificationMethod:
      type: object
      properties:
        id:
          type: string
          example: did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w#key-1
        type:
          type: string
          enum: [Ed25519VerificationKey2020, RsaVerificationKey2018, EcdsaSecp256k1VerificationKey2019]
        controller:
          type: string
          pattern: '^did:ion:.+$'
        publicKeyBase58:
          type: string
          example: 3M2mTGjHSXzpzVcxUjGCDNDHn5M9ux4rGqF8RpqBsHQA

    VerifyResponse:
      type: object
      properties:
        verified:
          type: boolean
          example: true
        error:
          type: string
          description: Error message if verification failed

    DIDState:
      type: object
      properties:
        did:
          type: string
          pattern: '^did:ion:.+$'
        document:
          $ref: '#/components/schemas/DIDDocument'
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        deactivated:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message
        timestamp:
          type: string
          format: date-time
